#!/bin/bash

# Author: Joseph Astier

# Test if there is a delphi_rest_api process running on gauss lstening on port 8123
#
# Running this script will either produce a 503 error if the delphi_rest_api process is unreachable,
# or something along the lines of "The Delphi REST API is running." if the process can be reached.

printf "Testing Delphi REST API status:\n"

remoteUrl="http://ivilab.org/delphi-api"
localUrl="http://localhost:8123"
target="/status"

url=$remoteUrl

call="curl -u me:ivilab4fun -s $url$target"

response=$($call)

printf "CALL:     $call\n"
printf "RESPONSE: $response\n"
